---
# tasks file for nginx
    - name: install epel-release
      yum: name=epel-release  

    - name: Update 
      yum: update_cache=yes 

    - name: install nginx and httpd-tools
      yum: 
        name:
        - nginx
        - httpd-tools  
        - tcpdump
        - net-tools
        - python-pip     
        state: latest

    - name: pip upgrade pip
      pip:
        name: pip
        extra_args: --upgrade

    - name: pip install passlib
      pip:
        name: passlib 
    
    - name: install libselinux-python and libsemanage-python 
      yum:
        name: 
        - libselinux-python
        - libsemanage-python
        state: latest        

    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: create directories for ssl certificates
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'
          
    - name: copy TLS key
      copy:
        src: nginx.key
        dest: "{{ key_file }}" 
        owner: root
        group: root
        mode: '0600'
      notify: restart nginx

    - name: copy TLS certificate
      copy: 
        src: nginx.crt
        dest: "{{ cert_file }}" 
        owner: root
        group: root
        mode: '0600'
      notify: restart nginx  
    
    - name: copy nginx config file
      template:
        src: nginx.conf.j2
        dest: "{{ conf_file }}"
        owner: root
        group: root
        mode: '0600'
      notify: restart nginx 
       
    - name: copy index.html
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx 

    - name: htpasswd
      htpasswd:
        path: /etc/nginx/htpasswd.users
        state: present
        name: "{{ basic_aut_username }}"
        password: "{{ basic_auth_password }}"
        crypt_scheme: md5_crypt
        owner: root
        group: root
        mode: 0644
      notify: restart nginx 

   # - name: Insert a rule on line 1
   #   iptables:
   #     chain: INPUT
   #     protocol: tcp
   #     destination_port: 443
   #     jump: ACCEPT
   #     action: insert
   #     rule_num: 1  

   # - name: Insert a rule on line 2
   #   iptables:
   #     chain: INPUT
   #     protocol: tcp
   #     destination_port: 80
   #     jump: ACCEPT
   #     action: insert
   #     rule_num: 2
    
    - name: open https
      firewalld:
        service: https
        permanent: yes
        state: enabled
    
    - name: open http
      firewalld:
        service: http
        permanent: yes
        state: enabled  
    
    - name: reload firewalld
      command: firewall-cmd --reload     
            
    - name: adding nginx to startup program
      service:
        name: nginx
        state: started
        enabled: yes
      notify: restart nginx   
